services:
  container:
#    build: .
    image: ${IMAGE:-ghcr.io/pokedo0/llmcord:latest}
    pull_policy: always
    network_mode: host
    restart: unless-stopped
    environment:
      GEMINI_COOKIE_PATH: /tmp/gemini_webapi
      ALL_PROXY: socks5h://127.0.0.1:40000
      all_proxy: socks5h://127.0.0.1:40000
      HTTP_PROXY: socks5h://127.0.0.1:40000
      HTTPS_PROXY: socks5h://127.0.0.1:40000
      http_proxy: socks5h://127.0.0.1:40000
      https_proxy: socks5h://127.0.0.1:40000
      NO_PROXY: localhost,127.0.0.1
      no_proxy: localhost,127.0.0.1
    volumes:
      - ./config:/app/config
      - ./gemini_cookies:/tmp/gemini_webapi
